# Generated by Django 4.2.3 on 2023-08-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
